# Generated by Django 4.1.3 on 2022-11-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_playlist_user_playlist_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='room.song'),
        ),
    ]
