# Generated by Django 4.1.3 on 2022-12-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_playlist_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
